### ISSUE TITLE
Kibana & Elasticsearch Failed to start

### ISSUE THREAD

**Issue by CyberReverend** [watsoninfosec/ElasticXDR#3]
Hey Ronnie,

I am attempting to follow the instructions you wrote to setup security for the ElasticXDR. After the certs/keys were created, I am now unable to start kibana and elastic. See logs below:

Job for elasticsearch.service failed because the control process exited with error code.
See "systemctl status elasticsearch.service" and "journalctl -xe" for details.
root@ubuntu:/etc/elasticsearch# journalctl -xe
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'e>
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'e>
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for u>
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO>
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'ex>
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'ex>
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for us>
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO >
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'exit>
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'exit>
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for user>
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO   >
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'exit-co>
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'exit-co>
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for user ro>
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO      >
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'exit-code'.
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for user root
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO        [m>
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'exit-code'.
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for user root
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO        [mon>
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'exit-code'.
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for user root
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO        [monitor>
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'exit-code'.
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for user root
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO        [monitori>
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit elasticsearch.service has entered the 'failed' state with result 'exit-code'.
Dec 31 13:11:21 ubuntu systemd[1]: Failed to start Elasticsearch.
-- Subject: A start job for unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit elasticsearch.service has finished with a failure.
-- 
-- The job identifier is 5647 and the job result is failed.
Dec 31 13:11:21 ubuntu sudo[9934]: pam_unix(sudo:session): session closed for user root
Dec 31 13:11:21 ubuntu filebeat[8576]: 2021-12-31T13:11:21.731-0800        INFO        [monitoring>
lines 1389-1411/1411 (END)
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- An ExecStart= process belonging to unit elasticsearch.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 31 13:11:21 ubuntu systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support

Let me know what you think.

**Comment by watsoninfosec** [comment]
Did you check to see if you can go back and comment out the cert lines and replace the https with http to see if it will start?

In your elasticsearch yml file and do that until it start then go un comment the lines again and see where it brakes at.

Basically, undo all your changes until it works then redo changes one by one and start it after each change is made to see where it fails.
